name: Build Pulu Firmware Builder

on:
  push:
    tags:
      - v1.*

jobs:
  compile_firmware_builder:
    runs-on: ubuntu-latest
    name: compile-firmware-builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/vives-projectwerk-2021/pulu-firmware-builder
        tags: |
          type=semver,pattern={{version}}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}