name: Build Pulu Firmware Builder

on:
  push:
    tags:
      - v1.*

jobs:
  compile_firmware_builder:
    runs-on: ubuntu-latest
    name: compile-firmware-builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ghcr.io/vives-projectwerk-2021/pulu-firmware-builder:${{ steps.get_version.outputs.VERSION }}
        build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}